### ISSUE TITLE
ButtonDevices are detected as echo WeMo switches

### ISSUE THREAD

**Issue by scobby** [michbeck100/pimatic-echo#13]
Hello,
All my Button device panels are added to the Echo. I dont think they will work.

**Comment by michbeck100** [comment]
All devices supported by pimatic-echo are detected als WeMo switches, because this plugin emulates a WeMo bridge. These switches are natively supported by Amazon echo. 
For buttons just the first button works. And it can only be switched on. When switching off nothing will happen. 
@scobby: Aren't  your Buttons working?

**Comment by scobby** [comment]
Didnt test the button. If that is the definition, its ok.
