### ISSUE TITLE
Plugin does not work anymore

### ISSUE THREAD

**Issue by mathiaslehmann** [michbeck100/pimatic-echo#67]
Hello, had to notice yesterday unfortunately that I can no longer control device over Alexa. She said the device is not responding. Was not completely home even last week, so the system has not changed. My idea was now to delete all devices in the Alexa app. Unfortunately, I find since no devices with Alexa. I am in possession of an Echo Dot 2nd generation and Echo Dot 3rd generation. The plugin is also up to date. Has anyone found similar problems? So far, it's a mystery to me what happened. Have the bad guess that something has changed in Alexa. Can someone help? thanks

**Comment by michbeck100** [comment]
Apparently Amazon changed something with the latest updates to their echos. See https://github.com/bwssytems/ha-bridge/issues/1133 or https://github.com/bwssytems/ha-bridge/issues/1130
I'm already trying to start the plugin under port 80 to see if it helps. Didn't work, yet. I will use this issue to track my progress

**Comment by michbeck100** [comment]
@mathiaslehmann Are you using the latest version of `pimatic-echo`? Because the default port is `9876`. You should see the used port during startup of pimatic in the log: 
```
started hue emulator on port <<port>>
```
If you are running on port 80, you might have to remove all your devices from Alexa. And then search for devices again. According to https://github.com/bwssytems/ha-bridge/issues/1133 you have to delete every device before. I haven't tried this myself, yet, because I didn't have time.

**Comment by michbeck100** [comment]
@mathiaslehmann I had to make some changes to make it work again, but with the latest version 0.5.4 you should be fine again. Please make sure to remove all previous devices from alexa.amazon.com. The new devices will be of type `Royal Phillips Electronics intelligent device`. If you still find devices of type `dimmable light`, make sure they get removed. You might have to remove every single device by its own. The "Remove all" button doesn't seem to work properly sometimes.

**Comment by mathiaslehmann** [comment]
Great, it works again. Thank you for solving the problem.
